#!/bin/bash

#=========== Additional Script==================
#...
#===============================================

systemctl stop "$SERVICENAME.service" || true
systemctl disable "$SERVICENAME.service" || true
systemctl daemon-reload
echo 'done'
