name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Vet
        working-directory: ./src
        run: go vet ./...

      - name: Test
        working-directory: ./src
        run: go test -race ./...

      - name: Build
        working-directory: ./src
        run: CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o /dev/null .
